// South Atlantic Sites — listings data. One entry per flyer in the Flyers folder.
// Fields: name, address, city, type, price, size, zoning, available, use, broker, highlights, flyer (Drive link), id (Drive file id),
// featured (true = show on the homepage), img (photo path), crop (vertical crop % for the homepage card).
// Updated 2026-09-11 · 22 listings
const LISTINGS = [
  {"name": "203 Capcom Ave – Suite 100", "address": "203 Capcom Ave, Suite 100", "city": "Wake Forest, NC 27587", "type": "For Lease", "price": "$18.50 PSF NNN", "size": "1,819 SF", "zoning": "HB", "available": "July 1, 2026", "use": "Flex / Light Industrial", "broker": "Joe Cabral & Shipman Northcutt", "highlights": "Flex space in Capital Commerce Center adjacent to The Factory retail complex. Quick access to US-1.", "flyer": "https://drive.google.com/file/d/1KHsnMtjyyItTjfV7Ewwl9QHd0LA6woDr/view", "id": "1KHsnMtjyyItTjfV7Ewwl9QHd0LA6woDr", "img": "img/listings/203-capcom-ave-suite-100.png", "crop": 21},
  {"name": "203 Capcom Ave – Suite 114", "address": "203 Capcom Ave, Suite 114", "city": "Wake Forest, NC 27587", "type": "For Lease", "price": "$18.50 PSF NNN", "size": "8,029 SF", "zoning": "HB", "available": "March 1, 2026", "use": "Flex / Retail / Assembly", "broker": "Joe Cabral & Shipman Northcutt", "highlights": "Large flex suite with loading dock. Assembly use allowed by-right. Adjacent to The Factory destination retail.", "flyer": "https://drive.google.com/file/d/1ZCou8ukkqrzdEB47VVQeLz8VxMf-a0-A/view", "id": "1ZCou8ukkqrzdEB47VVQeLz8VxMf-a0-A", "featured": 4, "img": "img/listings/203-capcom-ave-suite-114.png", "crop": 21},
  {"name": "832 Purser Dr", "address": "832 Purser Dr", "city": "Raleigh, NC 27603", "type": "For Lease", "price": "$7,400/mo Modified Gross", "size": "7,000 SF", "zoning": "LI (Garner)", "available": "Immediately", "use": "Light Industrial / Service", "broker": "Cam Wilson", "highlights": "Fully conditioned flex space, 2 motorized roll-up doors, 3-phase/200V power, mezzanine. 6–7 min from Downtown Raleigh.", "flyer": "https://drive.google.com/file/d/1UWkh85PKnCogSAqJqwtwTitW0lpNntHB/view", "id": "1UWkh85PKnCogSAqJqwtwTitW0lpNntHB", "img": "img/listings/832-purser-dr.png", "crop": 21},
  {"name": "Stonehenge Building – Ste 204", "address": "2301 Stonehenge Dr, Suite 204", "city": "Raleigh, NC 27615", "type": "For Lease", "price": "$25.00 PSF Modified Gross", "size": "1,130 SF", "zoning": "OX-3", "available": "April 1, 2026", "use": "Professional Office", "broker": "Joe Cabral", "highlights": "Charming office building with upgraded lobby. Two large offices, kitchenette and private restroom. Adjacent Harris Teeter.", "flyer": "https://drive.google.com/file/d/1zPzxskcpyzHYAKAqFXsABQLgR4yrwM4O/view", "id": "1zPzxskcpyzHYAKAqFXsABQLgR4yrwM4O", "img": "img/listings/stonehenge-building-ste-204.png", "crop": 21},
  {"name": "Lynnwood Plaza – Suite 114", "address": "3721 Lynn Road, Suite 114", "city": "Raleigh, NC 27613", "type": "For Lease", "price": "$20.00 PSF NNN + $4.89 TICAM", "size": "2,116 SF", "zoning": "NX-3", "available": "Available", "use": "Office / Retail", "broker": "Joe Cabral", "highlights": "Corner suite in Lynnwood Plaza off Lynn Rd near Glenwood Ave: 3 offices, open work area, 2 bathrooms, reception. Freshly painted, new lighting, tenant selects flooring. 13,000 VPD.", "flyer": "https://drive.google.com/file/d/1GK81IXCAQ7ReiCj6BJoyZZAEK6Eo8Idg/view", "id": "1GK81IXCAQ7ReiCj6BJoyZZAEK6Eo8Idg", "img": "img/listings/lynnwood-plaza-suite-114.png", "crop": 21},
  {"name": "Lynnwood Plaza – Suite 108", "address": "3721 Lynn Road, Suite 108", "city": "Raleigh, NC 27613", "type": "For Lease", "price": "$24.00 PSF NNN + $4.89 TICAM", "size": "1,182 SF", "zoning": "NX-3", "available": "December 2026", "use": "Office / Retail", "broker": "Joe Cabral", "highlights": "In-line suite in Lynnwood Plaza: open work area, office/conference room, bathroom. Near Target, Lowe's, and Cinemark Bistro. 13,000 VPD on Lynn Rd.", "flyer": "https://drive.google.com/file/d/17JRRFMSNO3IfrKv3eyRzlbov6MpEGogH/view", "id": "17JRRFMSNO3IfrKv3eyRzlbov6MpEGogH", "img": "img/listings/lynnwood-plaza-suite-108.png", "crop": 21},
  {"name": "Triangle East Collaborative", "address": "67 JR Rd, Suites 300 & 400", "city": "Selma, NC 27576", "type": "For Lease", "price": "$20.00 PSF NNN + $3.50 TICAM", "size": "7,441 – 23,070 SF", "zoning": "IB", "available": "Available", "use": "Retail / Food Hall", "broker": "Cam Wilson & Joe Cabral", "highlights": "Suite 300: 15,629 SF fully built-out food hall with equipment. Suite 400: 7,441 SF warm vanilla box. Visibility from I-95 and US-70 at Exit 97, across from Carolina Premium Outlets, adjacent to 435-acre Eastfield Crossing.", "flyer": "https://drive.google.com/file/d/1Jhiej6n8POxcDPtukYwzJ8HaGrD5Wucj/view", "id": "1Jhiej6n8POxcDPtukYwzJ8HaGrD5Wucj", "featured": 3, "img": "img/listings/triangle-east.png", "crop": 0},
  {"name": "1507 Greenfield St", "address": "1507 Greenfield St", "city": "Wilmington, NC 28401", "type": "For Lease", "price": "$11.50 PSF", "size": "8,301 SF", "zoning": "UMX", "available": "Available", "use": "Flex / Auto / Retail", "broker": "Payton Reid", "highlights": "Full city block, 20,000+ VPD, 4 garage bays, 150+ parking spaces. Adjacent to $66M Houston Moore Terrace redevelopment.", "flyer": "https://drive.google.com/file/d/1vxA413nV1KXw4X931uXzUX8K2AihkgLt/view", "id": "1vxA413nV1KXw4X931uXzUX8K2AihkgLt", "img": "img/listings/1507-greenfield-st.png", "crop": 21},
  {"name": "5000 Market St", "address": "5000 Market St", "city": "Wilmington, NC 28405", "type": "For Lease", "price": "Negotiable + $3.54 TICAM", "size": "1,931 SF", "zoning": "RB", "available": "Available", "use": "Retail / Office", "broker": "Payton Reid", "highlights": "40,000 VPD on Market Street. 0.7 mi from I-40, 0.85 mi from UNCW. Join two national retail tenants.", "flyer": "https://drive.google.com/file/d/10UpqJCBBlbvAJidoEBvfdCirc0j_Kokf/view", "id": "10UpqJCBBlbvAJidoEBvfdCirc0j_Kokf", "img": "img/listings/5000-market-st.png", "crop": 21},
  {"name": "Angier Ave at US-70", "address": "4731 Angier Ave", "city": "Durham, NC 27703", "type": "For Lease", "price": "Negotiable", "size": "2.19 Acres", "zoning": "CG / RS-20", "available": "Available", "use": "Commercial", "broker": "Cam Wilson", "highlights": "375' frontage on US-70 (37,000 VPD). Three parcels, 1.48 AC already commercial zoned.", "flyer": "https://drive.google.com/file/d/1QaJuW6xP8ibfeh322g_O-EtW8o7KAal1/view", "id": "1QaJuW6xP8ibfeh322g_O-EtW8o7KAal1", "img": "img/listings/angier-ave-at-us-70.png", "crop": 21},
  {"name": "2000 Citation Dr – Suite 120", "address": "2000 Citation Dr, Suite 120", "city": "Garner, NC 27529", "type": "For Lease", "price": "$15.47 PSF NNN", "size": "19,749 SF", "zoning": "IX-3", "available": "Sublease thru 2030", "use": "Industrial / Warehouse", "broker": "Cam Wilson", "highlights": "±1,500 SF finished office + 18,249 SF warehouse. 30' clear height, 4 dock-high doors, drive-in access. ESFR sprinklers, LED high-bays. Near I-40 & Jones Sausage Rd.", "flyer": "https://drive.google.com/file/d/1fMfLNsawU3wnSOTLPU4qsvKk6Ewr4eGb/view", "id": "1fMfLNsawU3wnSOTLPU4qsvKk6Ewr4eGb", "img": "img/listings/citation.png", "crop": 0},
  {"name": "6010 Glenwood Ave", "address": "6010 Glenwood Ave", "city": "Raleigh, NC 27612", "type": "Ground Lease", "price": "$175,000/yr", "size": "0.96 AC + 3,476 SF Bldg", "zoning": "CX3-PL", "available": "Available", "use": "Retail / QSR / Medical", "broker": "Mike Wilen", "highlights": "One of Raleigh's busiest retail nodes: 6.4M visits/yr, 37,500 VPD on Glenwood Ave (US-70). Full access via signalized intersection. Vacant former McDonald's with medical office upfit, 1.5 mi from Crabtree Valley Mall.", "flyer": "https://drive.google.com/file/d/1rIqDIWMjKVCzcFaTFIN5jml9rS7Oj-tu/view", "id": "1rIqDIWMjKVCzcFaTFIN5jml9rS7Oj-tu", "featured": 1, "img": "img/listings/glenwood.png", "crop": 21},
  {"name": "10754 NC HWY 50", "address": "10754 NC-50", "city": "Benson, NC 27504", "type": "For Sale or Ground Lease", "price": "$150,000/yr GL · Sale Negotiable", "size": "1.72 Acres", "zoning": "GB", "available": "Available", "use": "QSR / Drive-Thru / Retail", "broker": "Mike Wilen", "highlights": "Signalized intersection NC-210 & NC-50, 28,000+ combined VPD. 1 mile to I-40. Rough graded with all utilities to site. Full access until NCDOT construction 2029.", "flyer": "https://drive.google.com/file/d/1FYts1Ux6frc_RTM07T06xZ0VIXmwu4fw/view", "id": "1FYts1Ux6frc_RTM07T06xZ0VIXmwu4fw", "img": "img/listings/10754-nc-hwy-50.png", "crop": 21},
  {"name": "2791 Cornwallis Rd", "address": "2791 Cornwallis Rd", "city": "Garner, NC 27529", "type": "For Sale or Ground Lease", "price": "$1,375,000 · $125K/yr GL", "size": "0.92 Acres", "zoning": "GB", "available": "Available", "use": "Drive-Thru Restaurant", "broker": "Mike Wilen", "highlights": "Approved drive-thru plans on signalized corner. 13,000 VPD on Cleveland Rd. 1.5 mi from I-40/540.", "flyer": "https://drive.google.com/file/d/12HK0BWGSL2n20mPzjaSdItXWcIGXkbDV/view", "id": "12HK0BWGSL2n20mPzjaSdItXWcIGXkbDV", "featured": 6, "img": "img/listings/cornwallis.png", "crop": 21},
  {"name": "1002 Big Oak Court", "address": "1002 Big Oak Court", "city": "Knightdale, NC 27545", "type": "For Sale or Ground Lease", "price": "$1,200,000 · GL Negotiable", "size": "1.55 Acres", "zoning": "NMX-CD", "available": "Available", "use": "QSR / Retail / Commercial", "broker": "Cameron Wilson", "highlights": "Hard-corner exposure at Knightdale Blvd (US-64) & I-540: 38,000 VPD + 47,200 VPD on I-540. 130' frontage. Knightdale's population has more than doubled since 2010. New ParkStone phase approved nearby: 302 units + hotel + retail.", "flyer": "https://drive.google.com/file/d/1AncO7os_8KLCRVBtpQUrr5m492q6bL46/view", "id": "1AncO7os_8KLCRVBtpQUrr5m492q6bL46", "featured": 5, "img": "img/listings/bigoak.png", "crop": 21},
  {"name": "Hwy 17 & Washington Acres Rd", "address": "SEC Hwy 17 & Washington Acres Rd", "city": "Hampstead, NC 28411", "type": "For Sale or Ground Lease", "price": "Call to Discuss", "size": "7.55 Acres (3 Pads)", "zoning": "GB", "available": "Pads Available", "use": "QSR / Retail / Commercial", "broker": "Payton Reid", "highlights": "Join Royal Farms & Walmart. 50,000+ VPD. Fastest-growing town in NC (35.5% since 2020). $120K+ HH income.", "flyer": "https://drive.google.com/file/d/1t_Eu7jcAu51OG-qh23n4TR4rqvn6OTm_/view", "id": "1t_Eu7jcAu51OG-qh23n4TR4rqvn6OTm_", "featured": 2, "img": "img/listings/hwy-17-washington-acres-rd.png", "crop": 21},
  {"name": "1548 E Williams St", "address": "1548 E Williams St", "city": "Apex, NC 27539", "type": "For Sale or Lease", "price": "$12,500/mo · Sale Negotiable", "size": "6.10 Acres", "zoning": "PC-CZ", "available": "Available", "use": "Commercial / Drive-Thru", "broker": "Cam Wilson", "highlights": "600' frontage on NC-55 (45,500 VPD). Adjacent to $3B Veridea development and planned NC Children's Hospital.", "flyer": "https://drive.google.com/file/d/1mtRidQ4JK0vAmFblGPvyI9PcYSzXV3_X/view", "id": "1mtRidQ4JK0vAmFblGPvyI9PcYSzXV3_X", "img": "img/listings/williams.png", "crop": 21},
  {"name": "6453 NC-55 – Vacant Daycare", "address": "6453 NC-55", "city": "Durham, NC 27713", "type": "For Sale or Lease", "price": "Negotiable", "size": "7,800 SF / 4.75 Acres", "zoning": "CN (Durham County)", "available": "June 1, 2026", "use": "Daycare / Childcare Facility", "broker": "Cam Wilson", "highlights": "Purpose-built daycare at SWC of NC-55 & Hopson Rd on the edge of RTP. 23,000 VPD, 411' frontage, 8 classrooms, 8,500+ SF fenced playground. Seller willing to subdivide building or parcel.", "flyer": "https://drive.google.com/file/d/1nFgKJVB4XNIrOvpH4SWFMN-M95Np0lEP/view", "id": "1nFgKJVB4XNIrOvpH4SWFMN-M95Np0lEP", "img": "img/listings/6453-nc-55-vacant-daycare.png", "crop": 21},
  {"name": "2704 Triple Oak Dr", "address": "2704 Triple Oak Dr", "city": "Morrisville, NC 27560", "type": "For Sale", "price": "Call for Details", "size": "±0.93 Acres + 1,669 SF house (3 BR / 2.5 BA)", "zoning": "ORD", "available": "Available", "use": "Office / Research & Development Site with House", "broker": "Cam Wilson", "highlights": "Interior lot off Triple Oak Drive in Town of Cary ETJ. ORD zoning allows development. Move-in-ready house, well/septic, crawl space, HVAC. 24×24 carport. Minutes to RDU, I-40, Airport Blvd.", "flyer": "https://drive.google.com/file/d/1P1FK0yFEy7ebFASIDIHSJypBGKVP7WWb/view", "id": "1P1FK0yFEy7ebFASIDIHSJypBGKVP7WWb", "img": "img/listings/2704-triple-oak-dr.png", "crop": 21},
  {"name": "Firetower & Greys Mill Rd", "address": "NEC Firetower Rd & Greys Mill Rd", "city": "Louisburg, NC 27549", "type": "For Sale", "price": "Call for Details", "size": "32 Acres", "zoning": "AR", "available": "Available", "use": "Residential Development", "broker": "Cameron Wilson", "highlights": "12 potential lots per soil study. Franklin County pop +11.7% since 2020. Significant housing shortfall.", "flyer": "https://drive.google.com/file/d/1Y6IYHXXvggLm94GWqoOkOUOBNeD4PAT8/view", "id": "1Y6IYHXXvggLm94GWqoOkOUOBNeD4PAT8", "img": "img/listings/firetower-greys-mill-rd.png", "crop": 21},
  {"name": "NC-98 & Old Murray Dr", "address": "NC-98 & Old Murray Dr", "city": "Wake Forest, NC 27587", "type": "For Sale", "price": "Contact Brokers", "size": "~37.75 Acres", "zoning": "HD", "available": "Available", "use": "Residential Development", "broker": "Mike Wilen & Shipman Northcutt", "highlights": "Infill assemblage with 950' frontage on NC-98 in Wake Forest. Utilities at site. Buyer controls annexation.", "flyer": "https://drive.google.com/file/d/1lZCDaxxynRYZWwi0mctS6SWqqTvj7w1c/view", "id": "1lZCDaxxynRYZWwi0mctS6SWqqTvj7w1c", "img": "img/listings/nc-98-old-murray-dr.png", "crop": 21},
  {"name": "Jones Printing – Downtown Sanford", "address": "107 Charlotte Ave & 104 Hawkins Ave", "city": "Sanford, NC 27330", "type": "For Sale", "price": "$700K RE · $1.05M Business", "size": "10,500 SF / 0.73 AC", "zoning": "Opportunity Zone", "available": "Available", "use": "Properties + Business", "broker": "Shipman Northcutt", "highlights": "100+ year old profitable printing business sold with real estate. Downtown Sanford Opportunity Zone.", "flyer": "https://drive.google.com/file/d/10lbyGSdjL1-UXkic8kreeullSq-4raxc/view", "id": "10lbyGSdjL1-UXkic8kreeullSq-4raxc", "img": "img/listings/jones-printing-downtown-sanford.png", "crop": 21}
];
